---
apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
    service: productpage
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: productpage
  type: {{.Values.ServiceType}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage
  {{- if .Values.nocalhost.annotations.path.productpage }}
  annotations:
    nocalhost.dev: |-
      {{ .Files.Get .Values.nocalhost.annotations.path.productpage | nindent 6 }}
  {{- end }}
  labels:
    app: productpage
    app.kubernetes.io/name: productpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: productpage
      app: productpage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: productpage
        app: productpage
    spec:
      containers:
      - name: productpage
        image: codingcorp-docker.pkg.coding.net/nocalhost/bookinfo/productpage
        imagePullPolicy: IfNotPresent
        command: ['python', 'productpage.py', '9080']
        ports:
        - containerPort: 9080
        readinessProbe:
          tcpSocket:
            port: 9080
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        {{- with .Values.resources.productpage }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: tmp
        emptyDir: {}
